### PR TITLE
Language template update

### PR DESCRIPTION
**Pull request by codifryed**
The .pot file was out of date and missing quite a few i18n lines.

I regenerated the language template and synced the Author, License,
Description, etc. from the original. About 160 new translations,
a handful of case changes and a few removals that are no longer
present in the source code.

### CODE REVIEW

**Comment by joshreisner** [comment]
Thank you! This is in the plugin now.

I'm pretty clueless about this stuff. Is there more I should be doing to make this more multilingual? Should I be managing this file whenever I add/update strings?

This file I think came about because this one guy wanted to translate the plugin into Polish. We ended up using translate.wordpress.org for that, I added him as a "translation manager" I think and this file here wasn't needed further (as far as I know).

I've seen it translated into French (Quebec) and Spanish (Cancun) and would love to get that into translate.wordpress.org somehow so that people didn't need to duplicate their efforts.

**Comment by codifryed** [comment]
Glad I can help! 

You are right, in that translate.wordpress.org generates its own (pot) template and would seem to make this one superfluous. The only issue 'really' comes when one wants to do thier own translation files (.po), either through a program like poedit (the old way), or through a translating plugin like Loco. 

I think the recommendation is to use t.wp.org but update the pot file when adding new Strings.

I went about it this way because I had at first submitted translations to t.wp.org (in German), nothing happened and I wasn't sure what the state was with editors & managers there. I noticed the French translations looking damn near 100%, but nothing was accepted and no official language pack for them, even though they do have an editor for their locale. I saw the polish had a language pack with only a 77% completion, And had no way to quickly get a translation up for people to look at. Hence I've done it this way. (at about 11% everything on the front page is translated)

There are translations by contributers in quite a few languages...

I agree that there should be a better way, as it's not that obvious/intuitive on t.wp.org and it's definitely not clear how to communicate with the "Locale Manager" or whoever.  Getting peoples own translations uploaded and synced is relatively a simple process, but accepted and put out in the awesomeness of autoupdated language packs is not so straightforward. 

I'm more than willing to helpout if I can. I can at least be the editor(PTE) for the german locale (I'll then get help to get the translation finished). I'm not sure though, if you have to make the request or if I can do it. I believe it's done here: https://make.wordpress.org/polyglots/

Anywho, nice chatting :)

**Comment by joshreisner** [comment]
That'd be awesome, thanks! I'll request you on the polyglots page. Do you have a WP account? Is it the same username?

**Comment by FlipperPA** [comment]
Howdy friends, I'm not much of a WordPress person, but figured I'd mention TransiFex. It is used for crowdsourcing translations for the Wagtail CMS with a lot of success (I'm a Django person, heh):

https://www.transifex.com/torchbox/wagtail/

Basically you bring in a source .po file and specify what languages you want to target, and it's interface makes it straightforward for collaborate with people world wide for translations. I'm not sure if WordPress has its own facilities for this, but we've had really good success with it. Have an awesome weekend!

**Comment by joshreisner** [comment]
Thanks @FlipperPA, that's pretty much what translate.wordpress.org does as well.

**Comment by codifryed** [comment]
@joshreisner yepp, same username: codifryed There seems to also be a Cross-Locale PTE possibility. I could help with other locals that way... just thinking aloud. 

@FlipperPA looks great, especially for Wagtail.

**Comment by FlipperPA** [comment]
I'd volunteer to help out with the Arabic translation, but I'm guessing we won't get too much penetration into that market! :)

**Comment by joshreisner** [comment]
@FlipperPA really? Do you have a WP.org account? I can request you be added. It's true that there aren't many Arabic-language sites listed on aa.org, but maybe they're just waiting for a good meeting list plugin. 

On the other hand, I'm not sure how well the plugin will do in an RTL context, so it might be a big project...

**Comment by joshreisner** [comment]
@codifryed I made the request and I think it was denied? I can't tell. I think we ran into this with French as well. Hmmmmmmmm....

I don't know how to move this forward.

**Comment by joshreisner** [comment]
Whoops, here is the link: https://make.wordpress.org/polyglots/2018/01/21/hello-polyglots-i-am-the-284/

**Comment by codifryed** [comment]
Hi @joshreisner . ha! Denied! I love it. No worries, you try stuff. Since I was mentioned in the post I got a notification about it. I replied hoping for some clarification on how I can then move forward. And just to be clear about where I'm coming from, it's absolutely true that I am not a native speaker. I am however surrounded by them and speak the language fluently. I have though got together several native speakers willing to help me do the work, if I take care of the technical side. As I explained in my post, I just wanted to help out and didn't realize that translations were regulated in this manner. If I had known that the translations I just threw up 6 months ago would be up for review, I would have gone about it quite differently. I really think this plugin is very helpful and will continue to be. I wouldn't complain though if someone else came along and got the translation done. ;-) Till then I'll just keep on keepin' on. 
Thanks anyway!

**Comment by joshreisner** [comment]
@codifryed thanks for your persistence!

If you don't mind me asking, where are you? What's the site you're working on?

**Comment by codifryed** [comment]
hey @joshreisner, I don't mind you asking at all. I live near Berlin and in relation to this plugin we're working on an inter-regional german ACA website(germany-austria-switzerland-belgium). Still in development but coming along.

**Pull request merged**
